name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - '*'
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
env:
  BASE_URL: ${{secrets.BASE_URL}}  
jobs:   
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://dev-nuxt-corporate.g.kuroco.app/direct/menu/github/"
          webhook_secret: "abd1c816e196edb0c626d44ccff524f5"
          data: '{"single_zip":"0","domain":"dev-nuxt-corporate.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
